name: Mingw

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - {os: windows-latest, tclbranch: main, arch: mingw64, cpu: x86_64}
          - {os: windows-latest, tclbranch: main, arch: mingw32, cpu: i686}
          - {os: windows-latest, tclbranch: core-8-6-13, arch: mingw64, cpu: x86_64}
          - {os: windows-latest, tclbranch: core-8-6-13, arch: mingw32, cpu: i686}
    defaults:
      run:
        shell: msys2 {0}

    - name: Set up msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.arch }}
        path-type: minimal
        release: true
        update: false
        install: mingw-w64-${{matrix.cpu}}-gcc make

    - name: Verify toolchain
      run: |
        gcc -v
        make -v

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Tcl
      id: tcl-setup-step
      uses: apnadkarni/tcl-setup@v1
      with:
        tcl-osver: ${{ matrix.os }}
        tcl-branch: ${{ matrix.tclbranch }}
        tcl-toolchain: 'mingw64'
        tcl-arch: ${{ matrix.arch }}

    - name: Build extension
      id: tcl-build-step
      uses: apnadkarni/tcl-build-extension@main
      with:
        tcl-dotest: ${{ matrix.dotest }}

