name: Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        tclbranch:
          - core-8-6-13
          - main
    env:
      TCLSUBDIR: ${{ matrix.tclbranch }}
      TCLDIR: /tmp/tcl/${{ matrix.tclbranch }}

    steps:
    - name: Install libtommath
      id: tommath
      run: |
       sudo apt-get update
       sudo apt-get install libtommath-dev

    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Cache Tcl build
      id: tcl-cache
      uses: actions/cache@v4
      with:
        path: ${{ env.TCLDIR }}
        key: ${{ runner.os }}-tcl-${{ env.TCLSUBDIR }}

    - name: Checkout Tcl
      if: steps.tcl-cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: tcltk/tcl
        ref: ${{ matrix.tclbranch }}
        path: tcl-${{ matrix.tclbranch }}

    - name: Build Tcl
      if: steps.tcl-cache.outputs.cache-hit != 'true'
      working-directory: tcl-${{ matrix.tclbranch }}/unix
      run: |
        mkdir build
        cd build
        ../configure --prefix=${{ env.TCLDIR }} || (cat config.log && exit 1)
        make
        make install

    - name: Configure
      run: |
        mkdir build
        cd build
        ../configure --with-tcl=${{ env.TCLDIR }}/lib --enable-64bit

    - name: Make
      run: |
        cd build
        make

    - name: Test
      run: |
        cd build
        make test
      env:
        ERROR_ON_FAILURES: 1
