name: Ubuntu

on:
  workflow_dispatch:
    inputs:
      tcltag:  # User input for selecting Tcl tag
        description: 'Tcl version'
        required: true
        type: choice
        options:
          - '["core-9-0-0"]'
          - '["core-8-6-13"]'
          - '["main"]'
          - '["core-8-6-branch"]'
          - '["core-8-6-13", "core-9-0-0"]'
          - '["core-8-6-13", "core-9-0-0", "main", "core-8-6-branch"]'
        default: '["core-8-6-13", "core-9-0-0"]'
      osver:  # User input for selecting OS
        description: 'OS version'
        required: true
        type: choice
        options:
          - '["ubuntu-latest"]'
          - '["ubuntu-20.04"]'
          - '["ubuntu-22.04"]'
          - '["ubuntu-24.04"]'
          - '["ubuntu-20.04", "ubuntu-22.04", "ubuntu-24.04"]'
        default: '["ubuntu-20.04", "ubuntu-22.04", "ubuntu-24.04"]'
      dotest: # Whether tests should be run
        description: 'Run tests as well'
        required: false
        default: true
        type: boolean

jobs:
  build:
    strategy:
      matrix:
        os: ${{ fromJSON(github.event.inputs.osver) }}
        tclbranch: ${{ fromJSON(github.event.inputs.tcltag) }}

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup Tcl
      id: tcl-setup-step
      uses: apnadkarni/tcl-setup@v1
      with:
        tcl-osver: ${{ matrix.os }}
        tcl-branch: ${{ matrix.tclbranch }}

    - name: Build extension
      id: tcl-build-step
      uses: apnadkarni/tcl-build-extension@v1
      with:
        tcl-dotest: ${{ inputs.dotest }}
