name: Ubuntu

on:
  workflow_dispatch:
    inputs:
      tcltag:  # User input for selecting Tcl tag
        description: 'Tcl version'
        required: true
        type: choice
        options:
          - '["main"]'
          - '["core-8-6-13"]'
          - '["core-8-6-13", "main"]'
        default: '["core-8-6-13", "main"]'
      osver:  # User input for selecting OS
        description: 'OS version'
        required: true
        type: choice
        options:
          - '["ubuntu-latest"]'
          - '["ubuntu-20.04"]'
          - '["ubuntu-22.04"]'
          - '["ubuntu-24.04"]'
          - '["ubuntu-20.04", "ubuntu-22.04", "ubuntu-24.04"]'
        default: '["ubuntu-20.04"]'
      dotest: # Whether tests should be run
        description: 'Run tests as well'
        required: false
        default: true
        type: boolean

jobs:
  build:
    strategy:
      matrix:
        os: ${{ fromJSON(github.event.inputs.osver) }}
        tclbranch: ${{ fromJSON(github.event.inputs.tcltag) }}

    runs-on: ${{ matrix.os }}
    env:
      TCLSUBDIR: ${{ matrix.tclbranch }}
      TCLDIR: /tmp/tcl/${{ matrix.tclbranch }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install libtommath
      id: tommath
      run: |
       sudo apt-get update
       sudo apt-get install libtommath-dev

    - name: Cache Tcl build
      id: tcl-cache
      uses: actions/cache@v4
      with:
        path: ${{ env.TCLDIR }}
        key: ${{ runner.os }}-tcl-${{ env.TCLSUBDIR }}

    - name: Checkout Tcl
      if: steps.tcl-cache.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: tcltk/tcl
        ref: ${{ matrix.tclbranch }}
        path: tcl-${{ matrix.tclbranch }}

    - name: Build Tcl
      if: steps.tcl-cache.outputs.cache-hit != 'true'
      working-directory: tcl-${{ matrix.tclbranch }}/unix
      run: |
        mkdir build
        cd build
        ../configure --prefix=${{ env.TCLDIR }} || (cat config.log && exit 1)
        make
        make install

    - name: Configure
      run: |
        mkdir build
        cd build
        ../configure --with-tcl=${{ env.TCLDIR }}/lib --enable-64bit

    - name: Make
      run: |
        cd build
        make

    - name: Test
      if: github.event.inputs.dotest
      run: |
        cd build
        make test
      env:
        ERROR_ON_FAILURES: 1
